# Generated by Django 4.0.2 on 2022-02-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_posttag_post_tags_posttag_post_posttag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_pic', models.ImageField(null=True, upload_to='actionimages')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='rareapi.post')),
            ],
        ),
    ]
