# Generated by Django 4.0.2 on 2022-02-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_posttag_post_tags_posttag_post_posttag_tag'),
        ('rareapi', '0003_userpicture'),
    ]

    operations = [
    ]
