# Generated by Django 4.0.2 on 2022-02-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_alter_post_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(),
        ),
    ]
