# Generated by Django 4.0.2 on 2022-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_merge_20220217_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='theuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profileimages'),
        ),
        migrations.DeleteModel(
            name='userPicture',
        ),
    ]
