# Generated by Django 4.0.2 on 2022-02-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='game',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='action_pic',
            new_name='postimage',
        ),
    ]
