# Generated by Django 4.0.2 on 2022-02-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_tag'),
        ('rareapi', '0005_alter_post_publication_date'),
    ]

    operations = [
    ]
