# Generated by Django 4.0.2 on 2022-02-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_category'),
        ('rareapi', '0003_subscription'),
        ('rareapi', '0006_merge_0003_tag_0005_alter_post_publication_date'),
    ]

    operations = [
    ]
