# Generated by Django 4.0.2 on 2022-02-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0006_merge_20220215_1958'),
        ('rareapi', '0007_merge_20220215_1928'),
        ('rareapi', '0008_alter_post_publication_date'),
    ]

    operations = [
    ]
